# Generated by Django 5.0.6 on 2024-06-14 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_order_deliveryagent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="transaction_id",
        ),
    ]
